# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-29 17:01
from __future__ import unicode_literals

import apps.products.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Код')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name_plural': 'Аттрибуты',
                'verbose_name': 'Аттрибут',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.Attribute')),
            ],
            options={
                'verbose_name_plural': 'Значения аттрибутов',
                'verbose_name': 'Значение аттрибута',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.products.models.upload_category_location, verbose_name='Фото')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=128, null=True, verbose_name='slug')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name_plural': 'Производители',
                'verbose_name': 'Производитель',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('string_facets', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='текстовые парамеры')),
                ('number_facets', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='числовые параметры')),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Тэги')),
                ('suggest', models.CharField(blank=True, max_length=255, null=True, verbose_name='подсказки')),
                ('completion', models.CharField(blank=True, max_length=255, null=True, verbose_name='автодополнение')),
                ('fulltext_phonetic', models.CharField(blank=True, max_length=255, null=True, verbose_name='phonetic')),
                ('fulltext_russian', models.TextField(blank=True, max_length=255, null=True, verbose_name='russian')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='products.Category', verbose_name='Категория')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='products.Manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name_plural': 'Описание товаров',
                'verbose_name': 'Описание товара',
            },
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField(verbose_name='Артикул')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.products.models.upload_location, verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Созданно')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активированно')),
                ('measure_count', models.CharField(max_length=128, verbose_name='Количество (250/0.75)')),
                ('measure_value', models.CharField(max_length=128, verbose_name='Ед. измерения (гр./шт./л./мл./на чаше')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('stock_balance', models.IntegerField(verbose_name='Остаток на складе')),
                ('package_amount', models.IntegerField(verbose_name='Количество в упаковке')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ProductInfo', verbose_name='Инфо')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'verbose_name': 'Товар',
            },
        ),
    ]
