# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-05 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активированно'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активированно'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активированно'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активированно'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('draft', 'Черновик'), ('archive', 'Архив')], default='draft', max_length=128),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активированно'),
        ),
    ]
