# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-11 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190506_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='number_facets',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='string_facets',
        ),
        migrations.AddField(
            model_name='facetvalue',
            name='value',
            field=models.CharField(default='teset', max_length=255, verbose_name='Значение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinfo',
            name='facets',
            field=models.ManyToManyField(blank=True, null=True, to='products.FacetValue', verbose_name='парамеры'),
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='tags',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='products.Tags', verbose_name='Тэги'),
        ),
        migrations.RemoveField(
            model_name='facetvalue',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='facetvalue',
            unique_together=set([('facet', 'value')]),
        ),
    ]
