# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-20 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190520_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='facets',
        ),
        migrations.AddField(
            model_name='nfacetvalue',
            name='product_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.ProductInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinfo',
            name='nfacets',
            field=models.ManyToManyField(through='products.NFacetValue', to='products.NFacet', verbose_name='парамеры'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='sfacets',
            field=models.ManyToManyField(to='products.SFacetValue', verbose_name='парамеры'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(default='sa', max_length=128, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='tags',
            field=models.ManyToManyField(to='products.Tags', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='sfacetvalue',
            name='facet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.SFacet'),
        ),
        migrations.DeleteModel(
            name='Facet',
        ),
    ]
