# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-21 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190520_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sfacetvalue',
            old_name='value',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='sfacetvalue',
            unique_together=set([('facet', 'name')]),
        ),
    ]
