# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-24 19:26
from __future__ import unicode_literals

import apps.products.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190521_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активированно')),
                ('is_main', models.BooleanField(default=True, verbose_name='Главная')),
                ('src', models.ImageField(blank=True, null=True, upload_to=apps.products.models.upload_location, verbose_name='Фото')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
            ],
        ),
        migrations.RemoveField(
            model_name='productinstance',
            name='image',
        ),
        migrations.AddField(
            model_name='productinstance',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductInfo', verbose_name='Фото'),
        ),
    ]
