# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-26 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190524_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Созданно'),
            preserve_default=False,
        ),
    ]
