# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-26 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productinfo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductImage', verbose_name='Фото'),
        ),
    ]
