# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-27 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190526_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='completion',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='fulltext_phonetic',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='fulltext_russian',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='suggest',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главная'),
        ),
    ]
