# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-28 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190527_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='sfacets',
            field=models.ManyToManyField(blank=True, null=True, to='products.SFacetValue', verbose_name='парамеры'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='products.Tags', verbose_name='Тэги'),
        ),
    ]
