# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-28 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190528_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='nfacets',
            field=models.ManyToManyField(blank=True, through='products.NFacetValue', to='products.NFacet', verbose_name='парамеры'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='sfacets',
            field=models.ManyToManyField(blank=True, to='products.SFacetValue', verbose_name='парамеры'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='products.Tags', verbose_name='Тэги'),
        ),
    ]
