# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-31 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productimage_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='images',
        ),
        migrations.AddField(
            model_name='productimage',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.ProductInstance', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='product_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='products.ProductInfo', verbose_name='Инфо'),
        ),
    ]
