# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-09 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20190531_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='sku',
            field=models.BigIntegerField(unique=True, verbose_name='Артикул'),
        ),
    ]
