# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-27 06:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20190619_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='sales',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
    ]
