# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-25 19:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_collection_on_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='collections',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.CollectionImage'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='collections_set', to='products.ProductInstance'),
        ),
    ]
