# Generated by Django 2.2.4 on 2019-08-29 19:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20190826_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10, verbose_name='Базовая Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активированно'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='on_home',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активированно'),
        ),
        migrations.AlterField(
            model_name='nfacet',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='nfacet',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активированно'),
        ),
        migrations.AlterField(
            model_name='nfacetvalue',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(blank=True, default=False, verbose_name='Главная'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='collections',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активированно'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='sales',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='sfacet',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='sfacet',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активированно'),
        ),
        migrations.AlterField(
            model_name='sfacetvalue',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='sfacetvalue',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активированно'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активированно'),
        ),
    ]
