# Generated by Django 2.2.4 on 2020-12-08 11:40

import apps.sales.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductInstance')),
            ],
        ),
        migrations.CreateModel(
            name='SaleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, null=True, upload_to=apps.sales.models.upload_location, verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Созданно')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Активировано')),
                ('on_home', models.BooleanField(blank=True, default=False)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно')),
                ('categories', models.ManyToManyField(blank=True, through='sales.CategorySale', to='products.Category')),
                ('collections', models.ManyToManyField(blank=True, through='sales.CollectionSale', to='products.Collection')),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.SaleImage')),
                ('products', models.ManyToManyField(blank=True, through='sales.ProductSale', to='products.ProductInstance')),
            ],
            options={
                'verbose_name_plural': 'Акции',
                'verbose_name': 'Акция',
            },
        ),
        migrations.AddField(
            model_name='productsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sale'),
        ),
        migrations.AddField(
            model_name='collectionsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sale'),
        ),
        migrations.AddField(
            model_name='categorysale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sale'),
        ),
    ]
