# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-25 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_on_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='categories',
            field=models.ManyToManyField(blank=True, through='sales.CategorySale', to='products.Category'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='collections',
            field=models.ManyToManyField(blank=True, through='sales.CollectionSale', to='products.Collection'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(blank=True, through='sales.ProductSale', to='products.ProductInstance'),
        ),
    ]
