# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-26 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20190825_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
