# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-05 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190605_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsimage',
            name='instance',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.NewsImage', verbose_name='фото'),
        ),
    ]
