# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-05 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190605_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.NewsImage', verbose_name='фото'),
        ),
    ]
