# Generated by Django 2.2.4 on 2019-08-29 19:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190605_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активированно'),
        ),
        migrations.AlterField(
            model_name='news',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активировано'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительно'),
        ),
    ]
