# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-29 17:01
from __future__ import unicode_literals

import apps.home.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.home.models.upload_advertisements_location, verbose_name='фото')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name_plural': 'Объявления',
                'verbose_name': 'Объявление',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.home.models.upload_banner_location, verbose_name='Баннер')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name_plural': 'Баннеры',
                'verbose_name': 'Баннер',
            },
        ),
    ]
