# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-29 17:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Почта')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Активирован')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), editable=False, size=None, verbose_name='Права доступа')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='extra')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'verbose_name': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='extra')),
            ],
            options={
                'verbose_name_plural': 'Юр лица',
                'verbose_name': 'Юр лицо',
            },
        ),
        migrations.CreateModel(
            name='CompanyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Коэффициент')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='extra')),
            ],
            options={
                'verbose_name_plural': 'Статусы юр лица',
                'verbose_name': 'Статус юр лица',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Фамилия')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='extra')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Покупатели',
                'verbose_name': 'Покупатель',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='extra')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Сотрудники',
                'verbose_name': 'Сотрудник',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='users.CompanyStatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
    ]
